version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:./data/production.db
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-secret-key-here
      - NODE_ENV=production
    volumes:
      - sqlite_data:/app/data
    restart: unless-stopped

volumes:
  sqlite_data: